/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cajario_bridge_CobolBridge */

#ifndef _Included_com_cajario_bridge_CobolBridge
#define _Included_com_cajario_bridge_CobolBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cajario_bridge_CobolBridge
 * Method:    callCajaRio
 * Signature: (JID)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_cajario_bridge_CobolBridge_callCajaRio
  (JNIEnv *, jobject, jlong, jint, jdouble);

#ifdef __cplusplus
}
#endif
#endif
